print("1. Hoan Kiem lake")
print("2. Ngoc Son Temple")
print("3. Hanoi Cathedral")
print("4. Hanoi Opera House")
print("5. Thang Long Imperial Citadel")
print("6. Ho Chi Minh Mausoleum ")
print("7. West Lake")
print("8. Tran Quoc Pagoda")
print("9. One-pillar Pagoda")
print("10. Temple of Literature")